modLoader="javafml"
loaderVersion="[3,)"
license="MIT"

[[mods]]
modId="telepastries"
version="${file.jarVersion}"
displayName="TelePastries"
displayURL="https://github.com/Mrbysco/TelePastries"
authors="Mrbysco, ShyNieke"
description='''Pastries that teleport players.'''

[[dependencies.telepastries]]
modId="minecraft"
type="required"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.telepastries]]
modId="neoforge"
type="required"
versionRange="[20.6.78-beta,)"
ordering="NONE"
side="BOTH"