modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="telepastries"
version="${file.jarVersion}"
displayName="TelePastries"
displayURL="https://github.com/Mrbysco/TelePastries"
authors="Mrbysco, ShyNieke"
description='''Pastries that teleport players.'''

[[dependencies.telepastries]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.telepastries]]
modId="neoforge"
type="required"
versionRange="[21.0.143,)"
ordering="NONE"
side="BOTH"